version: "3"
services:
  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3333:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:5001/api
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/app/
  #     - /app/node_modules
  # server:
  #   build:
  #     context: ./server
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - PGDATABASE=postgres
  #     - PGHOST=db
  #   volumes:
  #     - ./server:/app/
  #     - /app/node_modules
  database:
    build:
      context: ./Chatscreen-Database
    volumes:
      - ashs-todo-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  ashs-todo-volume:
